In [1]:
from dotenv import load_dotenv
import os

load_dotenv()

CLIENT_ID = os.getenv("SPOTIFY_CLIENT_ID")
CLIENT_SECRET = os.getenv("SPOTIFY_CLIENT_SECRET")

print(CLIENT_ID)
print(CLIENT_SECRET[:8] + "...")

87fd4775a2564c5f989c6ac11a81c321
208cee53...

In [2]:
import pandas as pd

In [3]:
import spotipy
from spotipy.oauth2 import SpotifyOAuth

In [67]:
sp = spotipy.Spotify(
    auth_manager=SpotifyOAuth(
        client_id=CLIENT_ID,
        client_secret=CLIENT_SECRET,
        redirect_uri="http://127.0.0.1:8888/callback",
        scope=(
    "playlist-read-private "
    "playlist-read-collaborative "
    )
    )
)

In [68]:
me = sp.current_user()

print(me)

{'account_id': '2LeROuINAD', 'display_name': 'Duc Anh', 'external_urls': {'spotify': 'https://open.spotify.com/user/31b67t2tzug22sdprisyc37bni2u'}, 'followers': {'href': None, 'total': 1}, 'href': 'https://api.spotify.com/v1/users/31b67t2tzug22sdprisyc37bni2u', 'id': '31b67t2tzug22sdprisyc37bni2u', 'images': [{'height': 300, 'url': 'https://i.scdn.co/image/ab6775700000ee852647c4053736557f46a17490', 'width': 300}, {'height': 64, 'url': 'https://i.scdn.co/image/ab67757000003b822647c4053736557f46a17490', 'width': 64}], 'type': 'user', 'uri': 'spotify:user:31b67t2tzug22sdprisyc37bni2u'}

In [71]:
playlist_link = "https://open.spotify.com/playlist/0d8KH0AXcqUMoqVsYEWfBx?si=5r4WTCmcRkWo_qIUpN07bQ"
playlist_id = playlist_link.split("/")[-1].split("?")[0]

In [61]:
playlist_id

'37i9dQZEVXbNG2KDcFcKOF'

In [72]:
playlist = sp.playlist(playlist_id)
print(playlist["name"])

bebexmimi

In [73]:
data = sp.playlist_items(playlist_id)
data

{'href': 'https://api.spotify.com/v1/playlists/0d8KH0AXcqUMoqVsYEWfBx/items?offset=0&limit=50&additional_types=track',
 'items': [{'added_at': '2026-06-25T06:53:33Z',
   'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/31b67t2tzug22sdprisyc37bni2u'},
    'href': 'https://api.spotify.com/v1/users/31b67t2tzug22sdprisyc37bni2u',
    'id': '31b67t2tzug22sdprisyc37bni2u',
    'type': 'user',
    'uri': 'spotify:user:31b67t2tzug22sdprisyc37bni2u'},
   'is_local': False,
   'primary_color': None,
   'item': {'is_playable': True,
    'explicit': True,
    'type': 'track',
    'episode': False,
    'track': True,
    'album': {'is_playable': True,
     'type': 'album',
     'album_type': 'single',
     'href': 'https://api.spotify.com/v1/albums/6KFq3hJB6JnNvDbEHRvPoK',
     'id': '6KFq3hJB6JnNvDbEHRvPoK',
     'images': [{'height': 640,
       'url': 'https://i.scdn.co/image/ab67616d0000b273c7c031ce9d06b131f8563676',
       'width': 640},
      {'height': 300,
       'url': 'https://i.scdn.co/image/ab67616d00001e02c7c031ce9d06b131f8563676',
       'width': 300},
      {'height': 64,
       'url': 'https://i.scdn.co/image/ab67616d00004851c7c031ce9d06b131f8563676',
       'width': 64}],
     'name': 'Dracula (Remix)',
     'release_date': '2026-02-06',
     'release_date_precision': 'day',
     'uri': 'spotify:album:6KFq3hJB6JnNvDbEHRvPoK',
     'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/5INjqkS1o8h1imAzPqGZBb'},
       'href': 'https://api.spotify.com/v1/artists/5INjqkS1o8h1imAzPqGZBb',
       'id': '5INjqkS1o8h1imAzPqGZBb',
       'name': 'Tame Impala',
       'type': 'artist',
       'uri': 'spotify:artist:5INjqkS1o8h1imAzPqGZBb'},
      {'external_urls': {'spotify': 'https://open.spotify.com/artist/250b0Wlc5Vk0CoUsaCY84M'},
       'href': 'https://api.spotify.com/v1/artists/250b0Wlc5Vk0CoUsaCY84M',
       'id': '250b0Wlc5Vk0CoUsaCY84M',
       'name': 'JENNIE',
       'type': 'artist',
       'uri': 'spotify:artist:250b0Wlc5Vk0CoUsaCY84M'}],
     'external_urls': {'spotify': 'https://open.spotify.com/album/6KFq3hJB6JnNvDbEHRvPoK'},
     'total_tracks': 2},
    'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/5INjqkS1o8h1imAzPqGZBb'},
      'href': 'https://api.spotify.com/v1/artists/5INjqkS1o8h1imAzPqGZBb',
      'id': '5INjqkS1o8h1imAzPqGZBb',
      'name': 'Tame Impala',
      'type': 'artist',
      'uri': 'spotify:artist:5INjqkS1o8h1imAzPqGZBb'},
     {'external_urls': {'spotify': 'https://open.spotify.com/artist/250b0Wlc5Vk0CoUsaCY84M'},
      'href': 'https://api.spotify.com/v1/artists/250b0Wlc5Vk0CoUsaCY84M',
      'id': '250b0Wlc5Vk0CoUsaCY84M',
      'name': 'JENNIE',
      'type': 'artist',
      'uri': 'spotify:artist:250b0Wlc5Vk0CoUsaCY84M'}],
    'disc_number': 1,
    'track_number': 1,
    'duration_ms': 209720,
    'external_ids': {'isrc': 'USQX92600464'},
    'external_urls': {'spotify': 'https://open.spotify.com/track/5yvVYFDUpbnjcnRBgjwTzM'},
    'href': 'https://api.spotify.com/v1/tracks/5yvVYFDUpbnjcnRBgjwTzM',
    'id': '5yvVYFDUpbnjcnRBgjwTzM',
    'name': 'Dracula - JENNIE Remix',
    'uri': 'spotify:track:5yvVYFDUpbnjcnRBgjwTzM',
    'is_local': False},
   'video_thumbnail': {'url': None}},
  {'added_at': '2026-06-25T08:02:12Z',
   'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/31b67t2tzug22sdprisyc37bni2u'},
    'href': 'https://api.spotify.com/v1/users/31b67t2tzug22sdprisyc37bni2u',
    'id': '31b67t2tzug22sdprisyc37bni2u',
    'type': 'user',
    'uri': 'spotify:user:31b67t2tzug22sdprisyc37bni2u'},
   'is_local': False,
   'primary_color': None,
   'item': {'is_playable': True,
    'explicit': False,
    'type': 'track',
    'episode': False,
    'track': True,
    'album': {'is_playable': True,
     'type': 'album',
     'album_type': 'album',
     'href': 'https://api.spotify.com/v1/albums/5chTLnnxlxQVAgEv6YbEBe',
     'id': '5chTLnnxlxQVAgEv6YbEBe',
     'images': [{'height': 640,
       'url': 'https://i.scdn.co/image/ab67616d0000b273dfed999f959177dfc4f33cdc',
       'width': 640},
      {'height': 300,
       'url': 'https://i.scdn.co/image/ab67616d00001e02dfed999f959177dfc4f33cdc',
       'width': 300},
      {'height': 64,
       'url': 'https://i.scdn.co/image/ab67616d00004851dfed999f959177dfc4f33cdc',
       'width': 64}],
     'name': 'Cigarettes After Sex',
     'release_date': '2017-06-09',
     'release_date_precision': 'day',
     'uri': 'spotify:album:5chTLnnxlxQVAgEv6YbEBe',
     'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/1QAJqy2dA3ihHBFIHRphZj'},
       'href': 'https://api.spotify.com/v1/artists/1QAJqy2dA3ihHBFIHRphZj',
       'id': '1QAJqy2dA3ihHBFIHRphZj',
       'name': 'Cigarettes After Sex',
       'type': 'artist',
       'uri': 'spotify:artist:1QAJqy2dA3ihHBFIHRphZj'}],
     'external_urls': {'spotify': 'https://open.spotify.com/album/5chTLnnxlxQVAgEv6YbEBe'},
     'total_tracks': 10},
    'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/1QAJqy2dA3ihHBFIHRphZj'},
      'href': 'https://api.spotify.com/v1/artists/1QAJqy2dA3ihHBFIHRphZj',
      'id': '1QAJqy2dA3ihHBFIHRphZj',
      'name': 'Cigarettes After Sex',
      'type': 'artist',
      'uri': 'spotify:artist:1QAJqy2dA3ihHBFIHRphZj'}],
    'disc_number': 1,
    'track_number': 4,
    'duration_ms': 290146,
    'external_ids': {'isrc': 'USBQU1700034'},
    'external_urls': {'spotify': 'https://open.spotify.com/track/1oAwsWBovWRIp7qLMGPIet'},
    'href': 'https://api.spotify.com/v1/tracks/1oAwsWBovWRIp7qLMGPIet',
    'id': '1oAwsWBovWRIp7qLMGPIet',
    'name': 'Apocalypse',
    'uri': 'spotify:track:1oAwsWBovWRIp7qLMGPIet',
    'is_local': False},
   'video_thumbnail': {'url': None}},
  {'added_at': '2026-06-25T08:02:26Z',
   'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/31b67t2tzug22sdprisyc37bni2u'},
    'href': 'https://api.spotify.com/v1/users/31b67t2tzug22sdprisyc37bni2u',
    'id': '31b67t2tzug22sdprisyc37bni2u',
    'type': 'user',
    'uri': 'spotify:user:31b67t2tzug22sdprisyc37bni2u'},
   'is_local': False,
   'primary_color': None,
   'item': {'is_playable': True,
    'explicit': False,
    'type': 'track',
    'episode': False,
    'track': True,
    'album': {'is_playable': True,
     'type': 'album',
     'album_type': 'album',
     'href': 'https://api.spotify.com/v1/albums/63yRRBtLX8eqbOLD6f0y9U',
     'id': '63yRRBtLX8eqbOLD6f0y9U',
     'images': [{'height': 640,
       'url': 'https://i.scdn.co/image/ab67616d0000b2738324db1ae37be249aed887e7',
       'width': 640},
      {'height': 300,
       'url': 'https://i.scdn.co/image/ab67616d00001e028324db1ae37be249aed887e7',
       'width': 300},
      {'height': 64,
       'url': 'https://i.scdn.co/image/ab67616d000048518324db1ae37be249aed887e7',
       'width': 64}],
     'name': 'Cry',
     'release_date': '2019-10-25',
     'release_date_precision': 'day',
     'uri': 'spotify:album:63yRRBtLX8eqbOLD6f0y9U',
     'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/1QAJqy2dA3ihHBFIHRphZj'},
       'href': 'https://api.spotify.com/v1/artists/1QAJqy2dA3ihHBFIHRphZj',
       'id': '1QAJqy2dA3ihHBFIHRphZj',
       'name': 'Cigarettes After Sex',
       'type': 'artist',
       'uri': 'spotify:artist:1QAJqy2dA3ihHBFIHRphZj'}],
     'external_urls': {'spotify': 'https://open.spotify.com/album/63yRRBtLX8eqbOLD6f0y9U'},
     'total_tracks': 9},
    'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/1QAJqy2dA3ihHBFIHRphZj'},
      'href': 'https://api.spotify.com/v1/artists/1QAJqy2dA3ihHBFIHRphZj',
      'id': '1QAJqy2dA3ihHBFIHRphZj',
      'name': 'Cigarettes After Sex',
      'type': 'artist',
      'uri': 'spotify:artist:1QAJqy2dA3ihHBFIHRphZj'}],
    'disc_number': 1,
    'track_number': 7,
    'duration_ms': 256799,
    'external_ids': {'isrc': 'USBQU1900121'},
    'external_urls': {'spotify': 'https://open.spotify.com/track/7mDTvYD2ieE4Q28XFziMfJ'},
    'href': 'https://api.spotify.com/v1/tracks/7mDTvYD2ieE4Q28XFziMfJ',
    'id': '7mDTvYD2ieE4Q28XFziMfJ',
    'name': 'Cry',
    'uri': 'spotify:track:7mDTvYD2ieE4Q28XFziMfJ',
    'is_local': False},
   'video_thumbnail': {'url': None}},
  {'added_at': '2026-06-25T08:02:38Z',
   'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/31b67t2tzug22sdprisyc37bni2u'},
    'href': 'https://api.spotify.com/v1/users/31b67t2tzug22sdprisyc37bni2u',
    'id': '31b67t2tzug22sdprisyc37bni2u',
    'type': 'user',
    'uri': 'spotify:user:31b67t2tzug22sdprisyc37bni2u'},
   'is_local': False,
   'primary_color': None,
   'item': {'is_playable': True,
    'explicit': False,
    'type': 'track',
    'episode': False,
    'track': True,
    'album': {'is_playable': True,
     'type': 'album',
     'album_type': 'album',
     'href': 'https://api.spotify.com/v1/albums/5chTLnnxlxQVAgEv6YbEBe',
     'id': '5chTLnnxlxQVAgEv6YbEBe',
     'images': [{'height': 640,
       'url': 'https://i.scdn.co/image/ab67616d0000b273dfed999f959177dfc4f33cdc',
       'width': 640},
      {'height': 300,
       'url': 'https://i.scdn.co/image/ab67616d00001e02dfed999f959177dfc4f33cdc',
       'width': 300},
      {'height': 64,
       'url': 'https://i.scdn.co/image/ab67616d00004851dfed999f959177dfc4f33cdc',
       'width': 64}],
     'name': 'Cigarettes After Sex',
     'release_date': '2017-06-09',
     'release_date_precision': 'day',
     'uri': 'spotify:album:5chTLnnxlxQVAgEv6YbEBe',
     'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/1QAJqy2dA3ihHBFIHRphZj'},
       'href': 'https://api.spotify.com/v1/artists/1QAJqy2dA3ihHBFIHRphZj',
       'id': '1QAJqy2dA3ihHBFIHRphZj',
       'name': 'Cigarettes After Sex',
       'type': 'artist',
       'uri': 'spotify:artist:1QAJqy2dA3ihHBFIHRphZj'}],
     'external_urls': {'spotify': 'https://open.spotify.com/album/5chTLnnxlxQVAgEv6YbEBe'},
     'total_tracks': 10},
    'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/1QAJqy2dA3ihHBFIHRphZj'},
      'href': 'https://api.spotify.com/v1/artists/1QAJqy2dA3ihHBFIHRphZj',
      'id': '1QAJqy2dA3ihHBFIHRphZj',
      'name': 'Cigarettes After Sex',
      'type': 'artist',
      'uri': 'spotify:artist:1QAJqy2dA3ihHBFIHRphZj'}],
    'disc_number': 1,
    'track_number': 3,
    'duration_ms': 214680,
    'external_ids': {'isrc': 'USBQU1700033'},
    'external_urls': {'spotify': 'https://open.spotify.com/track/0yuAWlxq59xT3agQ965OxE'},
    'href': 'https://api.spotify.com/v1/tracks/0yuAWlxq59xT3agQ965OxE',
    'id': '0yuAWlxq59xT3agQ965OxE',
    'name': 'Sunsetz',
    'uri': 'spotify:track:0yuAWlxq59xT3agQ965OxE',
    'is_local': False},
   'video_thumbnail': {'url': None}},
  {'added_at': '2026-06-25T08:02:50Z',
   'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/31b67t2tzug22sdprisyc37bni2u'},
    'href': 'https://api.spotify.com/v1/users/31b67t2tzug22sdprisyc37bni2u',
    'id': '31b67t2tzug22sdprisyc37bni2u',
    'type': 'user',
    'uri': 'spotify:user:31b67t2tzug22sdprisyc37bni2u'},
   'is_local': False,
   'primary_color': None,
   'item': {'is_playable': True,
    'explicit': False,
    'type': 'track',
    'episode': False,
    'track': True,
    'album': {'is_playable': True,
     'type': 'album',
     'album_type': 'album',
     'href': 'https://api.spotify.com/v1/albums/5chTLnnxlxQVAgEv6YbEBe',
     'id': '5chTLnnxlxQVAgEv6YbEBe',
     'images': [{'height': 640,
       'url': 'https://i.scdn.co/image/ab67616d0000b273dfed999f959177dfc4f33cdc',
       'width': 640},
      {'height': 300,
       'url': 'https://i.scdn.co/image/ab67616d00001e02dfed999f959177dfc4f33cdc',
       'width': 300},
      {'height': 64,
       'url': 'https://i.scdn.co/image/ab67616d00004851dfed999f959177dfc4f33cdc',
       'width': 64}],
     'name': 'Cigarettes After Sex',
     'release_date': '2017-06-09',
     'release_date_precision': 'day',
     'uri': 'spotify:album:5chTLnnxlxQVAgEv6YbEBe',
     'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/1QAJqy2dA3ihHBFIHRphZj'},
       'href': 'https://api.spotify.com/v1/artists/1QAJqy2dA3ihHBFIHRphZj',
       'id': '1QAJqy2dA3ihHBFIHRphZj',
       'name': 'Cigarettes After Sex',
       'type': 'artist',
       'uri': 'spotify:artist:1QAJqy2dA3ihHBFIHRphZj'}],
     'external_urls': {'spotify': 'https://open.spotify.com/album/5chTLnnxlxQVAgEv6YbEBe'},
     'total_tracks': 10},
    'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/1QAJqy2dA3ihHBFIHRphZj'},
      'href': 'https://api.spotify.com/v1/artists/1QAJqy2dA3ihHBFIHRphZj',
      'id': '1QAJqy2dA3ihHBFIHRphZj',
      'name': 'Cigarettes After Sex',
      'type': 'artist',
      'uri': 'spotify:artist:1QAJqy2dA3ihHBFIHRphZj'}],
    'disc_number': 1,
    'track_number': 1,
    'duration_ms': 319560,
    'external_ids': {'isrc': 'USBQU1700031'},
    'external_urls': {'spotify': 'https://open.spotify.com/track/2xGjfbXZnI8uQDhukoQURQ'},
    'href': 'https://api.spotify.com/v1/tracks/2xGjfbXZnI8uQDhukoQURQ',
    'id': '2xGjfbXZnI8uQDhukoQURQ',
    'name': 'K.',
    'uri': 'spotify:track:2xGjfbXZnI8uQDhukoQURQ',
    'is_local': False},
   'video_thumbnail': {'url': None}},
  {'added_at': '2026-06-25T08:02:55Z',
   'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/31b67t2tzug22sdprisyc37bni2u'},
    'href': 'https://api.spotify.com/v1/users/31b67t2tzug22sdprisyc37bni2u',
    'id': '31b67t2tzug22sdprisyc37bni2u',
    'type': 'user',
    'uri': 'spotify:user:31b67t2tzug22sdprisyc37bni2u'},
   'is_local': False,
   'primary_color': None,
   'item': {'is_playable': True,
    'explicit': False,
    'type': 'track',
    'episode': False,
    'track': True,
    'album': {'is_playable': True,
     'type': 'album',
     'album_type': 'album',
     'href': 'https://api.spotify.com/v1/albums/5chTLnnxlxQVAgEv6YbEBe',
     'id': '5chTLnnxlxQVAgEv6YbEBe',
     'images': [{'height': 640,
       'url': 'https://i.scdn.co/image/ab67616d0000b273dfed999f959177dfc4f33cdc',
       'width': 640},
      {'height': 300,
       'url': 'https://i.scdn.co/image/ab67616d00001e02dfed999f959177dfc4f33cdc',
       'width': 300},
      {'height': 64,
       'url': 'https://i.scdn.co/image/ab67616d00004851dfed999f959177dfc4f33cdc',
       'width': 64}],
     'name': 'Cigarettes After Sex',
     'release_date': '2017-06-09',
     'release_date_precision': 'day',
     'uri': 'spotify:album:5chTLnnxlxQVAgEv6YbEBe',
     'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/1QAJqy2dA3ihHBFIHRphZj'},
       'href': 'https://api.spotify.com/v1/artists/1QAJqy2dA3ihHBFIHRphZj',
       'id': '1QAJqy2dA3ihHBFIHRphZj',
       'name': 'Cigarettes After Sex',
       'type': 'artist',
       'uri': 'spotify:artist:1QAJqy2dA3ihHBFIHRphZj'}],
     'external_urls': {'spotify': 'https://open.spotify.com/album/5chTLnnxlxQVAgEv6YbEBe'},
     'total_tracks': 10},
    'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/1QAJqy2dA3ihHBFIHRphZj'},
      'href': 'https://api.spotify.com/v1/artists/1QAJqy2dA3ihHBFIHRphZj',
      'id': '1QAJqy2dA3ihHBFIHRphZj',
      'name': 'Cigarettes After Sex',
      'type': 'artist',
      'uri': 'spotify:artist:1QAJqy2dA3ihHBFIHRphZj'}],
    'disc_number': 1,
    'track_number': 6,
    'duration_ms': 291640,
    'external_ids': {'isrc': 'USBQU1700036'},
    'external_urls': {'spotify': 'https://open.spotify.com/track/2KhrPRV0V1FS2l4eQMJUWt'},
    'href': 'https://api.spotify.com/v1/tracks/2KhrPRV0V1FS2l4eQMJUWt',
    'id': '2KhrPRV0V1FS2l4eQMJUWt',
    'name': 'Sweet',
    'uri': 'spotify:track:2KhrPRV0V1FS2l4eQMJUWt',
    'is_local': False},
   'video_thumbnail': {'url': None}},
  {'added_at': '2026-06-25T08:03:06Z',
   'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/31b67t2tzug22sdprisyc37bni2u'},
    'href': 'https://api.spotify.com/v1/users/31b67t2tzug22sdprisyc37bni2u',
    'id': '31b67t2tzug22sdprisyc37bni2u',
    'type': 'user',
    'uri': 'spotify:user:31b67t2tzug22sdprisyc37bni2u'},
   'is_local': False,
   'primary_color': None,
   'item': {'is_playable': True,
    'explicit': False,
    'type': 'track',
    'episode': False,
    'track': True,
    'album': {'is_playable': True,
     'type': 'album',
     'album_type': 'single',
     'href': 'https://api.spotify.com/v1/albums/7Li2N39grodaHIg2QU7MSk',
     'id': '7Li2N39grodaHIg2QU7MSk',
     'images': [{'height': 640,
       'url': 'https://i.scdn.co/image/ab67616d0000b273f20d15ff288e94492f7097eb',
       'width': 640},
      {'height': 300,
       'url': 'https://i.scdn.co/image/ab67616d00001e02f20d15ff288e94492f7097eb',
       'width': 300},
      {'height': 64,
       'url': 'https://i.scdn.co/image/ab67616d00004851f20d15ff288e94492f7097eb',
       'width': 64}],
     'name': 'I.',
     'release_date': '2012-07-21',
     'release_date_precision': 'day',
     'uri': 'spotify:album:7Li2N39grodaHIg2QU7MSk',
     'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/1QAJqy2dA3ihHBFIHRphZj'},
       'href': 'https://api.spotify.com/v1/artists/1QAJqy2dA3ihHBFIHRphZj',
       'id': '1QAJqy2dA3ihHBFIHRphZj',
       'name': 'Cigarettes After Sex',
       'type': 'artist',
       'uri': 'spotify:artist:1QAJqy2dA3ihHBFIHRphZj'}],
     'external_urls': {'spotify': 'https://open.spotify.com/album/7Li2N39grodaHIg2QU7MSk'},
     'total_tracks': 4},
    'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/1QAJqy2dA3ihHBFIHRphZj'},
      'href': 'https://api.spotify.com/v1/artists/1QAJqy2dA3ihHBFIHRphZj',
      'id': '1QAJqy2dA3ihHBFIHRphZj',
      'name': 'Cigarettes After Sex',
      'type': 'artist',
      'uri': 'spotify:artist:1QAJqy2dA3ihHBFIHRphZj'}],
    'disc_number': 1,
    'track_number': 1,
    'duration_ms': 286293,
    'external_ids': {'isrc': 'TCACJ1593857'},
    'external_urls': {'spotify': 'https://open.spotify.com/track/3W7KHojYGgYaoX9ogKO9hU'},
    'href': 'https://api.spotify.com/v1/tracks/3W7KHojYGgYaoX9ogKO9hU',
    'id': '3W7KHojYGgYaoX9ogKO9hU',
    'name': "Nothing's Gonna Hurt You Baby",
    'uri': 'spotify:track:3W7KHojYGgYaoX9ogKO9hU',
    'is_local': False},
   'video_thumbnail': {'url': None}},
  {'added_at': '2026-06-25T08:03:12Z',
   'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/31b67t2tzug22sdprisyc37bni2u'},
    'href': 'https://api.spotify.com/v1/users/31b67t2tzug22sdprisyc37bni2u',
    'id': '31b67t2tzug22sdprisyc37bni2u',
    'type': 'user',
    'uri': 'spotify:user:31b67t2tzug22sdprisyc37bni2u'},
   'is_local': False,
   'primary_color': None,
   'item': {'is_playable': True,
    'explicit': False,
    'type': 'track',
    'episode': False,
    'track': True,
    'album': {'is_playable': True,
     'type': 'album',
     'album_type': 'album',
     'href': 'https://api.spotify.com/v1/albums/63yRRBtLX8eqbOLD6f0y9U',
     'id': '63yRRBtLX8eqbOLD6f0y9U',
     'images': [{'height': 640,
       'url': 'https://i.scdn.co/image/ab67616d0000b2738324db1ae37be249aed887e7',
       'width': 640},
      {'height': 300,
       'url': 'https://i.scdn.co/image/ab67616d00001e028324db1ae37be249aed887e7',
       'width': 300},
      {'height': 64,
       'url': 'https://i.scdn.co/image/ab67616d000048518324db1ae37be249aed887e7',
       'width': 64}],
     'name': 'Cry',
     'release_date': '2019-10-25',
     'release_date_precision': 'day',
     'uri': 'spotify:album:63yRRBtLX8eqbOLD6f0y9U',
     'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/1QAJqy2dA3ihHBFIHRphZj'},
       'href': 'https://api.spotify.com/v1/artists/1QAJqy2dA3ihHBFIHRphZj',
       'id': '1QAJqy2dA3ihHBFIHRphZj',
       'name': 'Cigarettes After Sex',
       'type': 'artist',
       'uri': 'spotify:artist:1QAJqy2dA3ihHBFIHRphZj'}],
     'external_urls': {'spotify': 'https://open.spotify.com/album/63yRRBtLX8eqbOLD6f0y9U'},
     'total_tracks': 9},

In [8]:
data["items"][0]["item"]["album"]["id"]

'6KFq3hJB6JnNvDbEHRvPoK'

In [9]:
data["items"][0]["item"]["album"]["name"]

'Dracula (Remix)'

In [10]:
data["items"][0]["item"]["album"]["release_date"]

'2026-02-06'

In [11]:
data["items"][0]["item"]["album"]["total_tracks"]

2

In [12]:
data["items"][0]["item"]["album"]["external_urls"]["spotify"]

'https://open.spotify.com/album/6KFq3hJB6JnNvDbEHRvPoK'

In [13]:
album_list = []
for row in data["items"]:
    album_id = row["item"]["album"]["id"]
    name = row["item"]["album"]["name"]
    release_date = row["item"]["album"]["release_date"]
    total_tracks = row["item"]["album"]["total_tracks"]
    url = row["item"]["album"]["external_urls"]["spotify"]
    album_element = {"album_id": album_id, "name": name, "release_date": release_date, "total_tracks": total_tracks, "url":  url}
    album_list.append(album_element)

In [14]:
album_list

[{'album_id': '6KFq3hJB6JnNvDbEHRvPoK',
  'name': 'Dracula (Remix)',
  'release_date': '2026-02-06',
  'total_tracks': 2,
  'url': 'https://open.spotify.com/album/6KFq3hJB6JnNvDbEHRvPoK'},
 {'album_id': '5chTLnnxlxQVAgEv6YbEBe',
  'name': 'Cigarettes After Sex',
  'release_date': '2017-06-09',
  'total_tracks': 10,
  'url': 'https://open.spotify.com/album/5chTLnnxlxQVAgEv6YbEBe'},
 {'album_id': '63yRRBtLX8eqbOLD6f0y9U',
  'name': 'Cry',
  'release_date': '2019-10-25',
  'total_tracks': 9,
  'url': 'https://open.spotify.com/album/63yRRBtLX8eqbOLD6f0y9U'},
 {'album_id': '5chTLnnxlxQVAgEv6YbEBe',
  'name': 'Cigarettes After Sex',
  'release_date': '2017-06-09',
  'total_tracks': 10,
  'url': 'https://open.spotify.com/album/5chTLnnxlxQVAgEv6YbEBe'},
 {'album_id': '5chTLnnxlxQVAgEv6YbEBe',
  'name': 'Cigarettes After Sex',
  'release_date': '2017-06-09',
  'total_tracks': 10,
  'url': 'https://open.spotify.com/album/5chTLnnxlxQVAgEv6YbEBe'},
 {'album_id': '5chTLnnxlxQVAgEv6YbEBe',
  'name': 'Cigarettes After Sex',
  'release_date': '2017-06-09',
  'total_tracks': 10,
  'url': 'https://open.spotify.com/album/5chTLnnxlxQVAgEv6YbEBe'},
 {'album_id': '7Li2N39grodaHIg2QU7MSk',
  'name': 'I.',
  'release_date': '2012-07-21',
  'total_tracks': 4,
  'url': 'https://open.spotify.com/album/7Li2N39grodaHIg2QU7MSk'},
 {'album_id': '63yRRBtLX8eqbOLD6f0y9U',
  'name': 'Cry',
  'release_date': '2019-10-25',
  'total_tracks': 9,
  'url': 'https://open.spotify.com/album/63yRRBtLX8eqbOLD6f0y9U'},
 {'album_id': '63yRRBtLX8eqbOLD6f0y9U',
  'name': 'Cry',
  'release_date': '2019-10-25',
  'total_tracks': 9,
  'url': 'https://open.spotify.com/album/63yRRBtLX8eqbOLD6f0y9U'},
 {'album_id': '5chTLnnxlxQVAgEv6YbEBe',
  'name': 'Cigarettes After Sex',
  'release_date': '2017-06-09',
  'total_tracks': 10,
  'url': 'https://open.spotify.com/album/5chTLnnxlxQVAgEv6YbEBe'},
 {'album_id': '2nTZJADQTnOmXDJkbqX4fB',
  'name': "You're All I Want",
  'release_date': '2020-05-13',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/2nTZJADQTnOmXDJkbqX4fB'},
 {'album_id': '5XX1xVOP61GDQCGaZMLjhO',
  'name': 'Superclean, Vol. I',
  'release_date': '2017-11-03',
  'total_tracks': 6,
  'url': 'https://open.spotify.com/album/5XX1xVOP61GDQCGaZMLjhO'},
 {'album_id': '5TkaDC4mYSLBvdG6UrIB0v',
  'name': 'CINEMA',
  'release_date': '2021-06-25',
  'total_tracks': 13,
  'url': 'https://open.spotify.com/album/5TkaDC4mYSLBvdG6UrIB0v'},
 {'album_id': '5v7xYJyke25Nmt3l2R7YkR',
  'name': 'I Said I Love You First',
  'release_date': '2025-03-21',
  'total_tracks': 14,
  'url': 'https://open.spotify.com/album/5v7xYJyke25Nmt3l2R7YkR'},
 {'album_id': '03guxdOi12XJbnvxvxbpwG',
  'name': 'Submarine',
  'release_date': '2024-05-31',
  'total_tracks': 14,
  'url': 'https://open.spotify.com/album/03guxdOi12XJbnvxvxbpwG'},
 {'album_id': '3y8LtE30zPfQ4sXYRKvt2e',
  'name': 'Back To Me',
  'release_date': '2025-04-04',
  'total_tracks': 2,
  'url': 'https://open.spotify.com/album/3y8LtE30zPfQ4sXYRKvt2e'},
 {'album_id': '5TkaDC4mYSLBvdG6UrIB0v',
  'name': 'CINEMA',
  'release_date': '2021-06-25',
  'total_tracks': 13,
  'url': 'https://open.spotify.com/album/5TkaDC4mYSLBvdG6UrIB0v'},
 {'album_id': '03guxdOi12XJbnvxvxbpwG',
  'name': 'Submarine',
  'release_date': '2024-05-31',
  'total_tracks': 14,
  'url': 'https://open.spotify.com/album/03guxdOi12XJbnvxvxbpwG'},
 {'album_id': '03guxdOi12XJbnvxvxbpwG',
  'name': 'Submarine',
  'release_date': '2024-05-31',
  'total_tracks': 14,
  'url': 'https://open.spotify.com/album/03guxdOi12XJbnvxvxbpwG'},
 {'album_id': '5zyztYlsHoAeQKCsu8rVbo',
  'name': 'ái',
  'release_date': '2023-08-16',
  'total_tracks': 12,
  'url': 'https://open.spotify.com/album/5zyztYlsHoAeQKCsu8rVbo'},
 {'album_id': '5zyztYlsHoAeQKCsu8rVbo',
  'name': 'ái',
  'release_date': '2023-08-16',
  'total_tracks': 12,
  'url': 'https://open.spotify.com/album/5zyztYlsHoAeQKCsu8rVbo'},
 {'album_id': '5zyztYlsHoAeQKCsu8rVbo',
  'name': 'ái',
  'release_date': '2023-08-16',
  'total_tracks': 12,
  'url': 'https://open.spotify.com/album/5zyztYlsHoAeQKCsu8rVbo'},
 {'album_id': '71L9y03HASgkNoYodycslE',
  'name': 'FLVR',
  'release_date': '2024-09-18',
  'total_tracks': 4,
  'url': 'https://open.spotify.com/album/71L9y03HASgkNoYodycslE'},
 {'album_id': '71L9y03HASgkNoYodycslE',
  'name': 'FLVR',
  'release_date': '2024-09-18',
  'total_tracks': 4,
  'url': 'https://open.spotify.com/album/71L9y03HASgkNoYodycslE'},
 {'album_id': '71L9y03HASgkNoYodycslE',
  'name': 'FLVR',
  'release_date': '2024-09-18',
  'total_tracks': 4,
  'url': 'https://open.spotify.com/album/71L9y03HASgkNoYodycslE'},
 {'album_id': '1Iu5sceGmML4CeQ2f5Q6aO',
  'name': 'Superclean, Vol. II',
  'release_date': '2018-09-28',
  'total_tracks': 6,
  'url': 'https://open.spotify.com/album/1Iu5sceGmML4CeQ2f5Q6aO'},
 {'album_id': '3Qpia0Gp3Lu1IGTrb4anUM',
  'name': 'Dạo Này',
  'release_date': '2025-12-24',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/3Qpia0Gp3Lu1IGTrb4anUM'}]

In [15]:
data["items"][0]

{'added_at': '2026-06-25T06:53:33Z',
 'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/31b67t2tzug22sdprisyc37bni2u'},
  'href': 'https://api.spotify.com/v1/users/31b67t2tzug22sdprisyc37bni2u',
  'id': '31b67t2tzug22sdprisyc37bni2u',
  'type': 'user',
  'uri': 'spotify:user:31b67t2tzug22sdprisyc37bni2u'},
 'is_local': False,
 'primary_color': None,
 'item': {'is_playable': True,
  'explicit': True,
  'type': 'track',
  'episode': False,
  'track': True,
  'album': {'is_playable': True,
   'type': 'album',
   'album_type': 'single',
   'href': 'https://api.spotify.com/v1/albums/6KFq3hJB6JnNvDbEHRvPoK',
   'id': '6KFq3hJB6JnNvDbEHRvPoK',
   'images': [{'height': 640,
     'url': 'https://i.scdn.co/image/ab67616d0000b273c7c031ce9d06b131f8563676',
     'width': 640},
    {'height': 300,
     'url': 'https://i.scdn.co/image/ab67616d00001e02c7c031ce9d06b131f8563676',
     'width': 300},
    {'height': 64,
     'url': 'https://i.scdn.co/image/ab67616d00004851c7c031ce9d06b131f8563676',
     'width': 64}],
   'name': 'Dracula (Remix)',
   'release_date': '2026-02-06',
   'release_date_precision': 'day',
   'uri': 'spotify:album:6KFq3hJB6JnNvDbEHRvPoK',
   'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/5INjqkS1o8h1imAzPqGZBb'},
     'href': 'https://api.spotify.com/v1/artists/5INjqkS1o8h1imAzPqGZBb',
     'id': '5INjqkS1o8h1imAzPqGZBb',
     'name': 'Tame Impala',
     'type': 'artist',
     'uri': 'spotify:artist:5INjqkS1o8h1imAzPqGZBb'},
    {'external_urls': {'spotify': 'https://open.spotify.com/artist/250b0Wlc5Vk0CoUsaCY84M'},
     'href': 'https://api.spotify.com/v1/artists/250b0Wlc5Vk0CoUsaCY84M',
     'id': '250b0Wlc5Vk0CoUsaCY84M',
     'name': 'JENNIE',
     'type': 'artist',
     'uri': 'spotify:artist:250b0Wlc5Vk0CoUsaCY84M'}],
   'external_urls': {'spotify': 'https://open.spotify.com/album/6KFq3hJB6JnNvDbEHRvPoK'},
   'total_tracks': 2},
  'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/5INjqkS1o8h1imAzPqGZBb'},
    'href': 'https://api.spotify.com/v1/artists/5INjqkS1o8h1imAzPqGZBb',
    'id': '5INjqkS1o8h1imAzPqGZBb',
    'name': 'Tame Impala',
    'type': 'artist',
    'uri': 'spotify:artist:5INjqkS1o8h1imAzPqGZBb'},
   {'external_urls': {'spotify': 'https://open.spotify.com/artist/250b0Wlc5Vk0CoUsaCY84M'},
    'href': 'https://api.spotify.com/v1/artists/250b0Wlc5Vk0CoUsaCY84M',
    'id': '250b0Wlc5Vk0CoUsaCY84M',
    'name': 'JENNIE',
    'type': 'artist',
    'uri': 'spotify:artist:250b0Wlc5Vk0CoUsaCY84M'}],
  'disc_number': 1,
  'track_number': 1,
  'duration_ms': 209720,
  'external_ids': {'isrc': 'USQX92600464'},
  'external_urls': {'spotify': 'https://open.spotify.com/track/5yvVYFDUpbnjcnRBgjwTzM'},
  'href': 'https://api.spotify.com/v1/tracks/5yvVYFDUpbnjcnRBgjwTzM',
  'id': '5yvVYFDUpbnjcnRBgjwTzM',
  'name': 'Dracula - JENNIE Remix',
  'uri': 'spotify:track:5yvVYFDUpbnjcnRBgjwTzM',
  'is_local': False},
 'video_thumbnail': {'url': None}}

In [16]:
artist_list = []
for row in data["items"]:
    for key, value in row.items():
        if key == "item":
            for artist in value["artists"]:
                artist_dict={"artist_id": artist["id"], "artist_name": artist["name"], "external_url": artist["external_urls"]["spotify"]}
                artist_list.append(artist_dict)

In [17]:
artist_list

[{'artist_id': '5INjqkS1o8h1imAzPqGZBb',
  'artist_name': 'Tame Impala',
  'external_url': 'https://open.spotify.com/artist/5INjqkS1o8h1imAzPqGZBb'},
 {'artist_id': '250b0Wlc5Vk0CoUsaCY84M',
  'artist_name': 'JENNIE',
  'external_url': 'https://open.spotify.com/artist/250b0Wlc5Vk0CoUsaCY84M'},
 {'artist_id': '1QAJqy2dA3ihHBFIHRphZj',
  'artist_name': 'Cigarettes After Sex',
  'external_url': 'https://open.spotify.com/artist/1QAJqy2dA3ihHBFIHRphZj'},
 {'artist_id': '1QAJqy2dA3ihHBFIHRphZj',
  'artist_name': 'Cigarettes After Sex',
  'external_url': 'https://open.spotify.com/artist/1QAJqy2dA3ihHBFIHRphZj'},
 {'artist_id': '1QAJqy2dA3ihHBFIHRphZj',
  'artist_name': 'Cigarettes After Sex',
  'external_url': 'https://open.spotify.com/artist/1QAJqy2dA3ihHBFIHRphZj'},
 {'artist_id': '1QAJqy2dA3ihHBFIHRphZj',
  'artist_name': 'Cigarettes After Sex',
  'external_url': 'https://open.spotify.com/artist/1QAJqy2dA3ihHBFIHRphZj'},
 {'artist_id': '1QAJqy2dA3ihHBFIHRphZj',
  'artist_name': 'Cigarettes After Sex',
  'external_url': 'https://open.spotify.com/artist/1QAJqy2dA3ihHBFIHRphZj'},
 {'artist_id': '1QAJqy2dA3ihHBFIHRphZj',
  'artist_name': 'Cigarettes After Sex',
  'external_url': 'https://open.spotify.com/artist/1QAJqy2dA3ihHBFIHRphZj'},
 {'artist_id': '1QAJqy2dA3ihHBFIHRphZj',
  'artist_name': 'Cigarettes After Sex',
  'external_url': 'https://open.spotify.com/artist/1QAJqy2dA3ihHBFIHRphZj'},
 {'artist_id': '1QAJqy2dA3ihHBFIHRphZj',
  'artist_name': 'Cigarettes After Sex',
  'external_url': 'https://open.spotify.com/artist/1QAJqy2dA3ihHBFIHRphZj'},
 {'artist_id': '1QAJqy2dA3ihHBFIHRphZj',
  'artist_name': 'Cigarettes After Sex',
  'external_url': 'https://open.spotify.com/artist/1QAJqy2dA3ihHBFIHRphZj'},
 {'artist_id': '1QAJqy2dA3ihHBFIHRphZj',
  'artist_name': 'Cigarettes After Sex',
  'external_url': 'https://open.spotify.com/artist/1QAJqy2dA3ihHBFIHRphZj'},
 {'artist_id': '2sSGPbdZJkaSE2AbcGOACx',
  'artist_name': 'The Marías',
  'external_url': 'https://open.spotify.com/artist/2sSGPbdZJkaSE2AbcGOACx'},
 {'artist_id': '2sSGPbdZJkaSE2AbcGOACx',
  'artist_name': 'The Marías',
  'external_url': 'https://open.spotify.com/artist/2sSGPbdZJkaSE2AbcGOACx'},
 {'artist_id': '0C8ZW7ezQVs4URX5aX7Kqx',
  'artist_name': 'Selena Gomez',
  'external_url': 'https://open.spotify.com/artist/0C8ZW7ezQVs4URX5aX7Kqx'},
 {'artist_id': '5CiGnKThu5ctn9pBxv7DGa',
  'artist_name': 'benny blanco',
  'external_url': 'https://open.spotify.com/artist/5CiGnKThu5ctn9pBxv7DGa'},
 {'artist_id': '2sSGPbdZJkaSE2AbcGOACx',
  'artist_name': 'The Marías',
  'external_url': 'https://open.spotify.com/artist/2sSGPbdZJkaSE2AbcGOACx'},
 {'artist_id': '2sSGPbdZJkaSE2AbcGOACx',
  'artist_name': 'The Marías',
  'external_url': 'https://open.spotify.com/artist/2sSGPbdZJkaSE2AbcGOACx'},
 {'artist_id': '2sSGPbdZJkaSE2AbcGOACx',
  'artist_name': 'The Marías',
  'external_url': 'https://open.spotify.com/artist/2sSGPbdZJkaSE2AbcGOACx'},
 {'artist_id': '2sSGPbdZJkaSE2AbcGOACx',
  'artist_name': 'The Marías',
  'external_url': 'https://open.spotify.com/artist/2sSGPbdZJkaSE2AbcGOACx'},
 {'artist_id': '2sSGPbdZJkaSE2AbcGOACx',
  'artist_name': 'The Marías',
  'external_url': 'https://open.spotify.com/artist/2sSGPbdZJkaSE2AbcGOACx'},
 {'artist_id': '2sSGPbdZJkaSE2AbcGOACx',
  'artist_name': 'The Marías',
  'external_url': 'https://open.spotify.com/artist/2sSGPbdZJkaSE2AbcGOACx'},
 {'artist_id': '3diftVOq7aEIebXKkC34oR',
  'artist_name': 'tlinh',
  'external_url': 'https://open.spotify.com/artist/3diftVOq7aEIebXKkC34oR'},
 {'artist_id': '3diftVOq7aEIebXKkC34oR',
  'artist_name': 'tlinh',
  'external_url': 'https://open.spotify.com/artist/3diftVOq7aEIebXKkC34oR'},
 {'artist_id': '0XtC2d9ZVigYA7iMy5YkW0',
  'artist_name': '2Pillz',
  'external_url': 'https://open.spotify.com/artist/0XtC2d9ZVigYA7iMy5YkW0'},
 {'artist_id': '0qAJ604EZMbkbpZ9NN6W6d',
  'artist_name': 'WOKEUP',
  'external_url': 'https://open.spotify.com/artist/0qAJ604EZMbkbpZ9NN6W6d'},
 {'artist_id': '3diftVOq7aEIebXKkC34oR',
  'artist_name': 'tlinh',
  'external_url': 'https://open.spotify.com/artist/3diftVOq7aEIebXKkC34oR'},
 {'artist_id': '0XtC2d9ZVigYA7iMy5YkW0',
  'artist_name': '2Pillz',
  'external_url': 'https://open.spotify.com/artist/0XtC2d9ZVigYA7iMy5YkW0'},
 {'artist_id': '3diftVOq7aEIebXKkC34oR',
  'artist_name': 'tlinh',
  'external_url': 'https://open.spotify.com/artist/3diftVOq7aEIebXKkC34oR'},
 {'artist_id': '6TITnFVRcl0AcZ4syE7Toe',
  'artist_name': 'Low G',
  'external_url': 'https://open.spotify.com/artist/6TITnFVRcl0AcZ4syE7Toe'},
 {'artist_id': '3diftVOq7aEIebXKkC34oR',
  'artist_name': 'tlinh',
  'external_url': 'https://open.spotify.com/artist/3diftVOq7aEIebXKkC34oR'},
 {'artist_id': '6TITnFVRcl0AcZ4syE7Toe',
  'artist_name': 'Low G',
  'external_url': 'https://open.spotify.com/artist/6TITnFVRcl0AcZ4syE7Toe'},
 {'artist_id': '3diftVOq7aEIebXKkC34oR',
  'artist_name': 'tlinh',
  'external_url': 'https://open.spotify.com/artist/3diftVOq7aEIebXKkC34oR'},
 {'artist_id': '6TITnFVRcl0AcZ4syE7Toe',
  'artist_name': 'Low G',
  'external_url': 'https://open.spotify.com/artist/6TITnFVRcl0AcZ4syE7Toe'},
 {'artist_id': '2sSGPbdZJkaSE2AbcGOACx',
  'artist_name': 'The Marías',
  'external_url': 'https://open.spotify.com/artist/2sSGPbdZJkaSE2AbcGOACx'},
 {'artist_id': '0ZbgKh0FgPYeFP38nVaEGp',
  'artist_name': 'Obito',
  'external_url': 'https://open.spotify.com/artist/0ZbgKh0FgPYeFP38nVaEGp'}]

In [18]:
song_list = []
for row in data["items"]:
    song_id = row["item"]["id"]
    song_name = row["item"]["name"]
    song_duration = row["item"]["duration_ms"]
    song_url = row["item"]["external_urls"]["spotify"]
    song_added= row["added_at"]
    album_id = row["item"]["album"]["id"]
    artist_id = row["item"]["artists"][0]["id"]
    song_element = {"song_id": song_id, "song_name": song_name, "song_duration": song_duration, "song_url": song_url, "song_added": song_added, "album_id": album_id, "artist_id": artist_id}
    song_list.append(song_element)

In [19]:
song_list

[{'song_id': '5yvVYFDUpbnjcnRBgjwTzM',
  'song_name': 'Dracula - JENNIE Remix',
  'song_duration': 209720,
  'song_url': 'https://open.spotify.com/track/5yvVYFDUpbnjcnRBgjwTzM',
  'song_added': '2026-06-25T06:53:33Z',
  'album_id': '6KFq3hJB6JnNvDbEHRvPoK',
  'artist_id': '5INjqkS1o8h1imAzPqGZBb'},
 {'song_id': '1oAwsWBovWRIp7qLMGPIet',
  'song_name': 'Apocalypse',
  'song_duration': 290146,
  'song_url': 'https://open.spotify.com/track/1oAwsWBovWRIp7qLMGPIet',
  'song_added': '2026-06-25T08:02:12Z',
  'album_id': '5chTLnnxlxQVAgEv6YbEBe',
  'artist_id': '1QAJqy2dA3ihHBFIHRphZj'},
 {'song_id': '7mDTvYD2ieE4Q28XFziMfJ',
  'song_name': 'Cry',
  'song_duration': 256799,
  'song_url': 'https://open.spotify.com/track/7mDTvYD2ieE4Q28XFziMfJ',
  'song_added': '2026-06-25T08:02:26Z',
  'album_id': '63yRRBtLX8eqbOLD6f0y9U',
  'artist_id': '1QAJqy2dA3ihHBFIHRphZj'},
 {'song_id': '0yuAWlxq59xT3agQ965OxE',
  'song_name': 'Sunsetz',
  'song_duration': 214680,
  'song_url': 'https://open.spotify.com/track/0yuAWlxq59xT3agQ965OxE',
  'song_added': '2026-06-25T08:02:38Z',
  'album_id': '5chTLnnxlxQVAgEv6YbEBe',
  'artist_id': '1QAJqy2dA3ihHBFIHRphZj'},
 {'song_id': '2xGjfbXZnI8uQDhukoQURQ',
  'song_name': 'K.',
  'song_duration': 319560,
  'song_url': 'https://open.spotify.com/track/2xGjfbXZnI8uQDhukoQURQ',
  'song_added': '2026-06-25T08:02:50Z',
  'album_id': '5chTLnnxlxQVAgEv6YbEBe',
  'artist_id': '1QAJqy2dA3ihHBFIHRphZj'},
 {'song_id': '2KhrPRV0V1FS2l4eQMJUWt',
  'song_name': 'Sweet',
  'song_duration': 291640,
  'song_url': 'https://open.spotify.com/track/2KhrPRV0V1FS2l4eQMJUWt',
  'song_added': '2026-06-25T08:02:55Z',
  'album_id': '5chTLnnxlxQVAgEv6YbEBe',
  'artist_id': '1QAJqy2dA3ihHBFIHRphZj'},
 {'song_id': '3W7KHojYGgYaoX9ogKO9hU',
  'song_name': "Nothing's Gonna Hurt You Baby",
  'song_duration': 286293,
  'song_url': 'https://open.spotify.com/track/3W7KHojYGgYaoX9ogKO9hU',
  'song_added': '2026-06-25T08:03:06Z',
  'album_id': '7Li2N39grodaHIg2QU7MSk',
  'artist_id': '1QAJqy2dA3ihHBFIHRphZj'},
 {'song_id': '5E02BgqYNN9VzafXrYP6Np',
  'song_name': 'Heavenly',
  'song_duration': 286773,
  'song_url': 'https://open.spotify.com/track/5E02BgqYNN9VzafXrYP6Np',
  'song_added': '2026-06-25T08:03:12Z',
  'album_id': '63yRRBtLX8eqbOLD6f0y9U',
  'artist_id': '1QAJqy2dA3ihHBFIHRphZj'},
 {'song_id': '1v7ptGUBS2DbbRmfIG0hU2',
  'song_name': 'Touch',
  'song_duration': 292853,
  'song_url': 'https://open.spotify.com/track/1v7ptGUBS2DbbRmfIG0hU2',
  'song_added': '2026-06-25T08:03:16Z',
  'album_id': '63yRRBtLX8eqbOLD6f0y9U',
  'artist_id': '1QAJqy2dA3ihHBFIHRphZj'},
 {'song_id': '4xbN7giFhdGbSQTPyG178F',
  'song_name': 'John Wayne',
  'song_duration': 258013,
  'song_url': 'https://open.spotify.com/track/4xbN7giFhdGbSQTPyG178F',
  'song_added': '2026-06-25T08:03:22Z',
  'album_id': '5chTLnnxlxQVAgEv6YbEBe',
  'artist_id': '1QAJqy2dA3ihHBFIHRphZj'},
 {'song_id': '2cTvZSCqzjkTMkIypLxUFH',
  'song_name': "You're All I Want",
  'song_duration': 264453,
  'song_url': 'https://open.spotify.com/track/2cTvZSCqzjkTMkIypLxUFH',
  'song_added': '2026-06-25T08:03:31Z',
  'album_id': '2nTZJADQTnOmXDJkbqX4fB',
  'artist_id': '1QAJqy2dA3ihHBFIHRphZj'},
 {'song_id': '190IqlryWu91WBKeDgZqZz',
  'song_name': 'Only in My Dreams',
  'song_duration': 170893,
  'song_url': 'https://open.spotify.com/track/190IqlryWu91WBKeDgZqZz',
  'song_added': '2026-06-25T08:07:39Z',
  'album_id': '5XX1xVOP61GDQCGaZMLjhO',
  'artist_id': '2sSGPbdZJkaSE2AbcGOACx'},
 {'song_id': '410rGaFDJPwjsr9m9RPCkz',
  'song_name': 'All I Really Want Is You',
  'song_duration': 191800,
  'song_url': 'https://open.spotify.com/track/410rGaFDJPwjsr9m9RPCkz',
  'song_added': '2026-06-25T08:07:51Z',
  'album_id': '5TkaDC4mYSLBvdG6UrIB0v',
  'artist_id': '2sSGPbdZJkaSE2AbcGOACx'},
 {'song_id': '1DFmBjoeQN9DpOVTEewyx0',
  'song_name': 'Ojos Tristes (with The Marías)',
  'song_duration': 201920,
  'song_url': 'https://open.spotify.com/track/1DFmBjoeQN9DpOVTEewyx0',
  'song_added': '2026-06-25T08:07:55Z',
  'album_id': '5v7xYJyke25Nmt3l2R7YkR',
  'artist_id': '0C8ZW7ezQVs4URX5aX7Kqx'},
 {'song_id': '4gtIYSYu8u2ItBqrhCaChL',
  'song_name': 'Paranoia',
  'song_duration': 231786,
  'song_url': 'https://open.spotify.com/track/4gtIYSYu8u2ItBqrhCaChL',
  'song_added': '2026-06-25T08:08:00Z',
  'album_id': '03guxdOi12XJbnvxvxbpwG',
  'artist_id': '2sSGPbdZJkaSE2AbcGOACx'},
 {'song_id': '4pwJ6OujVQL3IpCr8KeXIg',
  'song_name': 'Nobody New',
  'song_duration': 215200,
  'song_url': 'https://open.spotify.com/track/4pwJ6OujVQL3IpCr8KeXIg',
  'song_added': '2026-06-25T08:08:05Z',
  'album_id': '3y8LtE30zPfQ4sXYRKvt2e',
  'artist_id': '2sSGPbdZJkaSE2AbcGOACx'},
 {'song_id': '1ShRHPAiiIrh0arZbSFmx1',
  'song_name': 'Heavy',
  'song_duration': 253213,
  'song_url': 'https://open.spotify.com/track/1ShRHPAiiIrh0arZbSFmx1',
  'song_added': '2026-06-25T08:08:08Z',
  'album_id': '5TkaDC4mYSLBvdG6UrIB0v',
  'artist_id': '2sSGPbdZJkaSE2AbcGOACx'},
 {'song_id': '0InIeZW4P6VO7dUGRM4AKH',
  'song_name': 'Sienna',
  'song_duration': 224840,
  'song_url': 'https://open.spotify.com/track/0InIeZW4P6VO7dUGRM4AKH',
  'song_added': '2026-06-25T08:08:13Z',
  'album_id': '03guxdOi12XJbnvxvxbpwG',
  'artist_id': '2sSGPbdZJkaSE2AbcGOACx'},
 {'song_id': '3siwsiaEoU4Kuuc9WKMUy5',
  'song_name': 'No One Noticed',
  'song_duration': 236906,
  'song_url': 'https://open.spotify.com/track/3siwsiaEoU4Kuuc9WKMUy5',
  'song_added': '2026-06-25T08:08:17Z',
  'album_id': '03guxdOi12XJbnvxvxbpwG',
  'artist_id': '2sSGPbdZJkaSE2AbcGOACx'},
 {'song_id': '6Y6qkxtOEbYoucZK3gRCtq',
  'song_name': 'nữ siêu anh hùng',
  'song_duration': 211436,
  'song_url': 'https://open.spotify.com/track/6Y6qkxtOEbYoucZK3gRCtq',
  'song_added': '2026-06-25T08:11:00Z',
  'album_id': '5zyztYlsHoAeQKCsu8rVbo',
  'artist_id': '3diftVOq7aEIebXKkC34oR'},
 {'song_id': '0uVHdmFQLlfm5gvAv9r1i7',
  'song_name': 'ghệ iu dấu của em ơi',
  'song_duration': 205138,
  'song_url': 'https://open.spotify.com/track/0uVHdmFQLlfm5gvAv9r1i7',
  'song_added': '2026-06-25T08:11:34Z',
  'album_id': '5zyztYlsHoAeQKCsu8rVbo',
  'artist_id': '3diftVOq7aEIebXKkC34oR'},
 {'song_id': '5ouxRyInSdRBQubu3KTd97',
  'song_name': 'nếu lúc đó',
  'song_duration': 263752,
  'song_url': 'https://open.spotify.com/track/5ouxRyInSdRBQubu3KTd97',
  'song_added': '2026-06-25T08:12:59Z',
  'album_id': '5zyztYlsHoAeQKCsu8rVbo',
  'artist_id': '3diftVOq7aEIebXKkC34oR'},
 {'song_id': '1BD3AOAttsy8P9BZKwdpB3',
  'song_name': 'HOP ON DA SHOW',
  'song_duration': 175876,
  'song_url': 'https://open.spotify.com/track/1BD3AOAttsy8P9BZKwdpB3',
  'song_added': '2026-06-25T08:13:20Z',
  'album_id': '71L9y03HASgkNoYodycslE',
  'artist_id': '3diftVOq7aEIebXKkC34oR'},
 {'song_id': '3COYA2vgfcUhDyRlVpZy5p',
  'song_name': 'PHÓNG ZÌN ZÌN',
  'song_duration': 202999,
  'song_url': 'https://open.spotify.com/track/3COYA2vgfcUhDyRlVpZy5p',
  'song_added': '2026-06-25T08:13:26Z',
  'album_id': '71L9y03HASgkNoYodycslE',
  'artist_id': '3diftVOq7aEIebXKkC34oR'},
 {'song_id': '1TcmqSx576eBcuTxTtcEAk',
  'song_name': 'NGÂN',
  'song_duration': 158905,
  'song_url': 'https://open.spotify.com/track/1TcmqSx576eBcuTxTtcEAk',
  'song_added': '2026-06-25T08:13:34Z',
  'album_id': '71L9y03HASgkNoYodycslE',
  'artist_id': '3diftVOq7aEIebXKkC34oR'},
 {'song_id': '02wNtFxlr9dLmZXKT5TIF5',
  'song_name': 'Over the Moon',
  'song_duration': 182900,
  'song_url': 'https://open.spotify.com/track/02wNtFxlr9dLmZXKT5TIF5',
  'song_added': '2026-06-26T23:49:51Z',
  'album_id': '1Iu5sceGmML4CeQ2f5Q6aO',
  'artist_id': '2sSGPbdZJkaSE2AbcGOACx'},
 {'song_id': '4MCP9l0QB9YN2LCkIy8mz4',
  'song_name': 'Dạo Này',
  'song_duration': 284288,
  'song_url': 'https://open.spotify.com/track/4MCP9l0QB9YN2LCkIy8mz4',
  'song_added': '2026-06-28T00:31:09Z',
  'album_id': '3Qpia0Gp3Lu1IGTrb4anUM',
  'artist_id': '0ZbgKh0FgPYeFP38nVaEGp'}]

In [20]:
album_df = pd.DataFrame(album_list)

In [21]:
album_df.head()

,album_id,name,release_date,total_tracks,url
0,6KFq3hJB6JnNvDbEHRvPoK,Dracula (Remix),2026-02-06,2,https://open.spotify.com/album/6KFq3hJB6JnNvDb...
1,5chTLnnxlxQVAgEv6YbEBe,Cigarettes After Sex,2017-06-09,10,https://open.spotify.com/album/5chTLnnxlxQVAgE...
2,63yRRBtLX8eqbOLD6f0y9U,Cry,2019-10-25,9,https://open.spotify.com/album/63yRRBtLX8eqbOL...
3,5chTLnnxlxQVAgEv6YbEBe,Cigarettes After Sex,2017-06-09,10,https://open.spotify.com/album/5chTLnnxlxQVAgE...
4,5chTLnnxlxQVAgEv6YbEBe,Cigarettes After Sex,2017-06-09,10,https://open.spotify.com/album/5chTLnnxlxQVAgE...

In [22]:
album_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   album_id      27 non-null     str
 1   name          27 non-null     str
 2   release_date  27 non-null     str
 3   total_tracks  27 non-null     int64
 4   url           27 non-null     str
dtypes: int64(1), str(4)
memory usage: 1.2 KB

In [23]:
album_df = album_df.drop_duplicates(subset=["album_id"], keep="first")

In [24]:
artist_df = pd.DataFrame(artist_list)

In [25]:
artist_df

,artist_id,artist_name,external_url
0,5INjqkS1o8h1imAzPqGZBb,Tame Impala,https://open.spotify.com/artist/5INjqkS1o8h1im...
1,250b0Wlc5Vk0CoUsaCY84M,JENNIE,https://open.spotify.com/artist/250b0Wlc5Vk0Co...
2,1QAJqy2dA3ihHBFIHRphZj,Cigarettes After Sex,https://open.spotify.com/artist/1QAJqy2dA3ihHB...
3,1QAJqy2dA3ihHBFIHRphZj,Cigarettes After Sex,https://open.spotify.com/artist/1QAJqy2dA3ihHB...
4,1QAJqy2dA3ihHBFIHRphZj,Cigarettes After Sex,https://open.spotify.com/artist/1QAJqy2dA3ihHB...
5,1QAJqy2dA3ihHBFIHRphZj,Cigarettes After Sex,https://open.spotify.com/artist/1QAJqy2dA3ihHB...
6,1QAJqy2dA3ihHBFIHRphZj,Cigarettes After Sex,https://open.spotify.com/artist/1QAJqy2dA3ihHB...
7,1QAJqy2dA3ihHBFIHRphZj,Cigarettes After Sex,https://open.spotify.com/artist/1QAJqy2dA3ihHB...
8,1QAJqy2dA3ihHBFIHRphZj,Cigarettes After Sex,https://open.spotify.com/artist/1QAJqy2dA3ihHB...
9,1QAJqy2dA3ihHBFIHRphZj,Cigarettes After Sex,https://open.spotify.com/artist/1QAJqy2dA3ihHB...
10,1QAJqy2dA3ihHBFIHRphZj,Cigarettes After Sex,https://open.spotify.com/artist/1QAJqy2dA3ihHB...
11,1QAJqy2dA3ihHBFIHRphZj,Cigarettes After Sex,https://open.spotify.com/artist/1QAJqy2dA3ihHB...
12,2sSGPbdZJkaSE2AbcGOACx,The Marías,https://open.spotify.com/artist/2sSGPbdZJkaSE2...
13,2sSGPbdZJkaSE2AbcGOACx,The Marías,https://open.spotify.com/artist/2sSGPbdZJkaSE2...
14,0C8ZW7ezQVs4URX5aX7Kqx,Selena Gomez,https://open.spotify.com/artist/0C8ZW7ezQVs4UR...
15,5CiGnKThu5ctn9pBxv7DGa,benny blanco,https://open.spotify.com/artist/5CiGnKThu5ctn9...
16,2sSGPbdZJkaSE2AbcGOACx,The Marías,https://open.spotify.com/artist/2sSGPbdZJkaSE2...
17,2sSGPbdZJkaSE2AbcGOACx,The Marías,https://open.spotify.com/artist/2sSGPbdZJkaSE2...
18,2sSGPbdZJkaSE2AbcGOACx,The Marías,https://open.spotify.com/artist/2sSGPbdZJkaSE2...
19,2sSGPbdZJkaSE2AbcGOACx,The Marías,https://open.spotify.com/artist/2sSGPbdZJkaSE2...
20,2sSGPbdZJkaSE2AbcGOACx,The Marías,https://open.spotify.com/artist/2sSGPbdZJkaSE2...
21,2sSGPbdZJkaSE2AbcGOACx,The Marías,https://open.spotify.com/artist/2sSGPbdZJkaSE2...
22,3diftVOq7aEIebXKkC34oR,tlinh,https://open.spotify.com/artist/3diftVOq7aEIeb...
23,3diftVOq7aEIebXKkC34oR,tlinh,https://open.spotify.com/artist/3diftVOq7aEIeb...
24,0XtC2d9ZVigYA7iMy5YkW0,2Pillz,https://open.spotify.com/artist/0XtC2d9ZVigYA7...
25,0qAJ604EZMbkbpZ9NN6W6d,WOKEUP,https://open.spotify.com/artist/0qAJ604EZMbkbp...
26,3diftVOq7aEIebXKkC34oR,tlinh,https://open.spotify.com/artist/3diftVOq7aEIeb...
27,0XtC2d9ZVigYA7iMy5YkW0,2Pillz,https://open.spotify.com/artist/0XtC2d9ZVigYA7...
28,3diftVOq7aEIebXKkC34oR,tlinh,https://open.spotify.com/artist/3diftVOq7aEIeb...
29,6TITnFVRcl0AcZ4syE7Toe,Low G,https://open.spotify.com/artist/6TITnFVRcl0AcZ...
30,3diftVOq7aEIebXKkC34oR,tlinh,https://open.spotify.com/artist/3diftVOq7aEIeb...
31,6TITnFVRcl0AcZ4syE7Toe,Low G,https://open.spotify.com/artist/6TITnFVRcl0AcZ...
32,3diftVOq7aEIebXKkC34oR,tlinh,https://open.spotify.com/artist/3diftVOq7aEIeb...
33,6TITnFVRcl0AcZ4syE7Toe,Low G,https://open.spotify.com/artist/6TITnFVRcl0AcZ...
34,2sSGPbdZJkaSE2AbcGOACx,The Marías,https://open.spotify.com/artist/2sSGPbdZJkaSE2...
35,0ZbgKh0FgPYeFP38nVaEGp,Obito,https://open.spotify.com/artist/0ZbgKh0FgPYeFP...

In [26]:
artist_df = artist_df.drop_duplicates(subset=["artist_id"], keep="first")

In [27]:
song_df = pd.DataFrame(song_list)

In [28]:
song_df = song_df.drop_duplicates(subset=["song_id"], keep="first")

In [29]:
album_df['release_date'] = pd.to_datetime(album_df['release_date'], errors='coerce')

In [30]:
song_df = pd.to_datetime(song_df['song_added'], errors='coerce')

In [75]:
token_info = sp.auth_manager.get_cached_token()
print(token_info.keys())

dict_keys(['access_token', 'token_type', 'expires_in', 'scope', 'expires_at', 'refresh_token'])

In [76]:
token_info = sp.auth_manager.get_cached_token()

print(token_info)

{'access_token': 'BQC-TfQCYZ7VOyWgArmqvT5af0RYtIHx3ROdygr_9VMgrxyisyupMMb9C92IjdXNoWuOIgUwtTRg4E2Yij0EGISn-JlOzPZ7tUiwM6-4yAa5E8HiUexxZ4W3akeOF0QXG5oR2EIZzflxd4PQW5PdbmwG6EbAG5UD0LDnRJ7WRIDEdWXIysi09h6hDfbjRJqSt7UANZfdNCa6db4xfTLk77wMbMEPzcUSlbg6CqhpgphE1FBMFR2uEbMrWgwpW-WiYU1pwHsf', 'token_type': 'Bearer', 'expires_in': 3600, 'scope': 'playlist-read-private playlist-read-collaborative ', 'expires_at': 1782676166, 'refresh_token': 'AQBLypQ9oOK_jRHMnV6PwxHtV0xzL9KFZoCwwPrE8YzBTbbvQDs-BfKUtct2PVZSnDapJPmTCJow0K4FKgofRs1LgXhP5lDcRXwlsGrXkBjc6Q6u_uE_1oTat979SlNvDEg'}

In [1]:
row["item"].keys()

NameError: name 'row' is not defined